class MarkDown

  def self.mark_down
    "# Guide\r\n\r\n这是一篇讲解如何正确使用 **Markdown** 的排版示例，学会这个很有必要，能让你的文章有更佳清晰的排版。\r\n\r\n> 引用文本：Markdown is a text formatting syntax inspired\r\n\r\n## 语法指导\r\n\r\n### 普通内容\r\n\r\n这段内容展示了在内容里面一些小的格式，
     比如：\r\n\r\n- **加粗** - `**加粗**`\r\n- *倾斜* - `*倾斜*`\r\n- ~~删除线~~ - `~~删除线~~`\r\n- `Code 标记` - ``Code 标记``\r\n- [超级链接](http://github.com) - `[超级链接](http://github.com)`\r\n- [username@gmail.com](mailto:username@gmail.com) - `[username@gmail
     .com](mailto:username@gmail.com)`\r\n\r\n### 提及用户\r\n\r\n@foo @bar @someone ... 通过 @ 可以在发帖和回帖里面提及用户，信息提交以后，被提及的用户将会收到系统通知。以便让他来关注这个帖子或回帖。\r\n\r\n### 表情符号 Emoji\r\n\r\n支持表情符号，你可以用系统默认的 Emo
     ji 符号（无法支持 Windows 用户）。\r\n也可以用图片的表情，输入 `:` 将会出现智能提示。\r\n\r\n#### 一些表情例子\r\n\r\n:smile: :laughing: :dizzy_face: :sob: :cold_sweat: :sweat_smile:  :cry: :triumph: :heart_eyes: :relaxed: :sunglasses: :weary:\r\n\r\n:+1: :-1: :100
     : :clap: :bell: :gift: :question: :bomb: :heart: :coffee: :cyclone: :bow: :kiss: :pray: :sweat_drops: :hankey: :exclamation: :anger:\r\n\r\n### 大标题 - Heading 3\r\n\r\n你可以选择使用 H2 至 H6，使用 ##(N) 打头，H1 不能使用，会自动转换成 H2。\r\n\r\n> NOTE: 别忘了  # 后面需要有空格！\r\n\r\n#### Heading 4\r\n\r\n##### Heading 5\r\n\r\n###### Heading 6\r\n\r\n### 图片\r\n\r\n```\r\n![alt 文本](http://image-path.png)\r\n![alt 文本](http://image-path.png \"图片 Title 值\")\r\n![设置图片宽度高度](http://image-path.png =300x200)\r \n![设置图片宽度](http://image-path.png =300x)\r\n![设置图片高度](http://image-path.png =x200)\r\n```\r\n\r\n### 代码块\r\n\r\n#### 普通\r\n\r\n```\r\n*emphasize*    **strong**\r\n_emphasize_    __strong__\r\n@a = 1\r\n```\r\n\r\n#### 语法高亮支持\r\n\r\n如果在 ```  后面更随语言名称，可以有语法高亮的效果哦，比如:\r\n\r\n##### 演示 Ruby 代码高亮\r\n\r\n```\r\nclass PostController < ApplicationController\r\n  def index\r\n    @posts = Post.last_actived.limit(10)\r\n  end\r\nend\r\n```\r\n\r\n##### 演示 Rails View 高亮\r\n\r\n`` `erb\r\n<%= @posts.each do |post| %>\r\n<div class=\"post\"></div>\r\n<% end %>\r\n```\r\n\r\n##### 演示 YAML 文件\r\n\r\n```yml\r\nzh-CN:\r\n  name: 姓名\r\n  age: 年龄\r\n```\r\n\r\n> Tip: 语言名称支持下面这些: `ruby`, `python`, `js`, `html`, `erb`, `css`, `coffe e`, `bash`, `json`, `yml`, `xml` ...\r\n\r\n### 有序、无序列表\r\n\r\n#### 无序列表\r\n\r\n- Ruby\r\n  - Rails\r\n    - ActiveRecord\r\n- Go\r\n  - Gofmt\r\n  - Revel\r\n- Node.js\r\n  - Koa\r\n  - Express\r\n\r\n#### 有序列表\r\n\r\n1. Node.js\r\n  1. Express\r\n   2. Koa\r\n  3. Sails\r\n2. Ruby\r\n  1. Rails\r\n  2. Sinatra\r\n3. Go\r\n\r\n### 表格\r\n\r\n如果需要展示数据什么的，可以选择使用表格哦\r\n\r\n| header 1 | header 3 |\r\n| -------- | -------- |\r\n| cell 1   | cell 2   |\r\n| cell 3   | cell 4   |\r\n| cell 5   |  cell 6   |\r\n\r\n### 段落\r\n\r\n留空白的换行，将会被自动转换成一个段落，会有一定的段落间距，便于阅读。\r\n\r\n请注意后面 Markdown 源代码的换行留空情况。\r\n\r\n### 视频插入\r\n\r\n目前支持 Youtube 和 Youku 两家的视频插入，你只需要复制视频播放页面，浏览器地址栏的 网页 URL 地址，并粘贴到话题／回复文本框，提交以后将自动转换成视频播放器。\r\n\r\n#### 例如\r\n\r\n**Youtube**\r\n\r\nhttps://www.youtube.com/watch?v=CvVvwh3BRq8\r\n\r\n**Vimeo**\r\n\r\nhttps://vimeo.com/199770305\r\n\r\n**Youku**\r\n\r\nhttp://v.youku.com/v_show/id_XMjQzMTY1MDk3Ng==.html\r\n\r\n···"
  end

end

