# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5f986959d82b4c38d5107272f0a7c8105bfcf0e2f7502438035412e01fcb2d706b8d2584b8b3b5e256005dd8e0e73bf5a141755d51d47d92e4a5347591d2430

test:
  secret_key_base: b082b4f687b328e3f03864dd075b13601a9c02f1c70880f2bb891145cb38d704648bfd7b91e40678a231d542a6cc58f257503dece58e97bd133b777009a591ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c10aa63787f3ac1fb6cc9d82134a9f210d69ad85a64ccfa677cbf6f07d4c07d3ac9dccdd5af2d1f7dc80cde7a1e29413adc776b4f9247564b8ed7bead3b6ee9d
